### PR TITLE
Added ucast option to cluster configuration

### PR DESCRIPTION
**Pull request by area42**
for example: set cluster ucast 'eth0:172.16.35.159'

-Mike

### CODE REVIEW

**Comment by dmbaturin** [comment]
A few questions:
1. Are you Mike Wessling himself, or you are relaying the patch?

Assuming you are,
2. "ucast" isn't really descriptive. Have you considered using a more descriptive name, such as "cluster-peer"?
3. Entering unverified interface:ip values doesn't really feel good. Have you considered changing the syntax so it's easier to verify, e.g. "cluster-peer 192.0.2.1 interface eth0"?

**Comment by area42** [comment]
Hi Daniil,

It is my first pull request so I am new at this.

1) Yes I am.
2)  ucast was the term we used internally to distinguish from the default
multicast.  And it is the name of the setting in ha.cf. I am happy to
change it.
3) The ethernet port is verified against the interface list but I do agree
that the syntax is nonstandard.  I probably need to look deeper at the
config.pm code to understand it enough to define a 2 argument command.

-Mike

**Comment by sanderv32** [comment]
What about:

set cluster interface eth0 peer 1.2.3.4

So without the peer it uses multicast and if peer is filled in it uses unicast. Then it's also possible to implement broadcast by adding it behind the peer:

set cluster interface eth0 peer 1.2.3.4 broadcast

**Comment by hagbard-01** [comment]
1.1.x is EOL, PR not relevant anymore

**Pull request closed without merging**
